name: met1
description: "MET - Smart Timetable & Student Hub"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Local Storage
  shared_preferences: ^2.3.4

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

  # Internationalization
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#080E24"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/

